// 从课程.docx解析的课程数据
export const ADDITIONAL_COURSES = [
  // 因果系列
  {
    id: '22',
    title: '疾病为什么会反复',
    content: '疾病反复的根本原因是没有找到真正的病因，只是控制了症状。需要理解因果规律，找到病因才能从根本上解决问题。',
    duration: '10分钟',
    module: '因果',
    season: '第1季',
    courseNumber: 2,
    relatedElements: ['气血', '循环'],
    relatedDiseases: ['慢性病', '反复发作的疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '23',
    title: '如何用两个字解读疾病',
    content: '用"因果"两个字解读疾病。因是病因，果是疾病症状。治病求因，找到病因才能治本。',
    duration: '10分钟',
    module: '因果',
    season: '第1季',
    courseNumber: 3,
    relatedElements: ['气血'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '24',
    title: '如何用因果解决疾病',
    content: '通过找到病因，消除病因，从根本上解决疾病问题。因果思维是健康调理的核心思维。',
    duration: '10分钟',
    module: '因果',
    season: '第1季',
    courseNumber: 4,
    relatedElements: ['气血', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '25',
    title: '找到病因就能去根',
    content: '找到病因并消除病因，疾病才能去根。病因在生活习惯、情绪、饮食等方面，需要全面排查。',
    duration: '10分钟',
    module: '因果',
    season: '第2季',
    courseNumber: 18,
    relatedElements: ['气血', '毒素', '情绪'],
    relatedDiseases: ['所有慢性病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '26',
    title: '不懂因果，错上加错',
    content: '如果不懂因果规律，只关注症状，往往会导致错上加错，病情加重。必须建立因果思维。',
    duration: '10分钟',
    module: '因果',
    season: '第1季',
    courseNumber: 5,
    relatedElements: ['气血', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },

  // 寒湿系列
  {
    id: '27',
    title: '预防流感的五个要素',
    content: '预防流感需要注意保暖、提升免疫力、保持卫生、合理饮食、充足休息五个要素。',
    duration: '10分钟',
    module: '寒湿',
    season: '第1季',
    courseNumber: 25,
    relatedElements: ['寒凉', '免疫'],
    relatedDiseases: ['感冒', '流感', '呼吸道感染'],
    isHidden: true,
    priority: 4
  },
  {
    id: '28',
    title: '温度解百病',
    content: '体温是健康的重要指标。体温低会导致免疫力下降、循环不畅、代谢缓慢。提升体温可以预防和改善多种疾病。',
    duration: '10分钟',
    module: '寒湿',
    season: '第1季',
    courseNumber: 46,
    relatedElements: ['寒凉', '循环', '气血', '免疫'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '29',
    title: '气血平衡，让你的生活变得更美好',
    content: '气血平衡是健康的基础。气血充足，身体机能正常；气血不足，各种疾病随之而来。',
    duration: '10分钟',
    module: '气血',
    season: '第2季',
    courseNumber: 25,
    relatedElements: ['气血', '循环'],
    relatedDiseases: ['气血不足引起的疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '30',
    title: '会坐月子能去病',
    content: '月子期间调养得当，可以去除很多妇科疾病。月子调养包括保暖、休息、营养、情绪管理等方面。',
    duration: '10分钟',
    module: '寒湿',
    season: '第2季',
    courseNumber: 25,
    relatedElements: ['寒凉', '气血', '毒素'],
    relatedDiseases: ['月子病', '妇科疾病'],
    isHidden: true,
    priority: 4
  },

  // 排毒系列
  {
    id: '31',
    title: '如何解读排毒反应',
    content: '排毒反应是身体在清理毒素时的正常反应，包括发热、乏力、头晕、皮肤变化等。要正确理解，不要误以为是病情加重。',
    duration: '10分钟',
    module: '排毒',
    season: '第1季',
    courseNumber: 18,
    relatedElements: ['毒素', '气血'],
    relatedDiseases: ['所有疾病调理过程'],
    isHidden: true,
    priority: 4
  },
  {
    id: '32',
    title: '你知道身体有哪八个救命的排毒口吗',
    content: '身体有八个重要的排毒口，包括汗腺、泌尿系统、呼吸系统、肠道等。了解并运用这些排毒口，可以有效排毒。',
    duration: '10分钟',
    module: '排毒',
    season: '第1季',
    courseNumber: 26,
    relatedElements: ['毒素', '循环'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '33',
    title: '排毒的四大好处',
    content: '排毒可以清除体内毒素，提升免疫力，改善循环，延缓衰老。是健康调理的重要环节。',
    duration: '10分钟',
    module: '排毒',
    season: '第1季',
    courseNumber: 27,
    relatedElements: ['毒素', '循环', '免疫', '气血'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '34',
    title: '让家人远离大病的秘密',
    content: '通过定期排毒、改善生活习惯、提升免疫力，可以让家人远离大病，保持健康。',
    duration: '10分钟',
    module: '排毒',
    season: '第1季',
    courseNumber: 23,
    relatedElements: ['毒素', '免疫', '气血'],
    relatedDiseases: ['所有慢性病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '35',
    title: '你欠身体的账还的越早，风险越小',
    content: '不良生活习惯、情绪压力等都是欠身体的健康账。越早还账，健康风险越小。',
    duration: '10分钟',
    module: '排毒',
    season: '第3季',
    courseNumber: 37,
    relatedElements: ['毒素', '气血', '循环'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },

  // 微循环系列
  {
    id: '36',
    title: '大病查出来为什么到晚期',
    content: '大病在早期时，微循环已经出现问题，但仪器检查不出来。等到查出时，往往已经是晚期。要重视身体的早期信号。',
    duration: '10分钟',
    module: '微循环',
    season: '第1季',
    courseNumber: 9,
    relatedElements: ['循环', '气血', '毒素'],
    relatedDiseases: ['癌症', '重大疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '37',
    title: '大病查出来为什么到晚期',
    content: '微循环是大病早期的重要信号。通过改善微循环，可以预防和改善重大疾病。',
    duration: '10分钟',
    module: '微循环',
    season: '第1季',
    courseNumber: 10,
    relatedElements: ['循环', '气血', '毒素'],
    relatedDiseases: ['癌症', '重大疾病'],
    isHidden: true,
    priority: 5
  },

  // 免疫力系列
  {
    id: '38',
    title: '这个世界上没有治百病的药，但是有调百病的方法',
    content: '药物只能治疗症状，不能治本。通过调理气血、循环、毒素等，才能从根本上改善健康。',
    duration: '10分钟',
    module: '免疫力',
    season: '第1季',
    courseNumber: 11,
    relatedElements: ['免疫', '气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '39',
    title: '我们的免疫力，为什么比十年前下降了',
    content: '免疫力下降的原因包括环境污染、不良生活习惯、情绪压力、营养不均衡等。需要全面提升免疫力。',
    duration: '10分钟',
    module: '免疫力',
    season: '第4季',
    courseNumber: 1,
    relatedElements: ['免疫', '气血', '毒素'],
    relatedDiseases: ['免疫力低下引起的疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '40',
    title: '孩子对不起，我们知道的太晚了',
    content: '很多疾病如果在早期干预，可以避免悲剧。家长要重视孩子的健康，及时预防和调理。',
    duration: '10分钟',
    module: '免疫力',
    season: '第3季',
    courseNumber: 52,
    relatedElements: ['免疫', '气血'],
    relatedDiseases: ['儿童疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '41',
    title: '父母体质好，孩子生病少',
    content: '父母的体质会影响孩子的健康。父母调理好身体，孩子生病会减少。',
    duration: '10分钟',
    module: '免疫力',
    season: '第2季',
    courseNumber: 35,
    relatedElements: ['免疫', '气血', '毒素'],
    relatedDiseases: ['儿童疾病'],
    isHidden: true,
    priority: 4
  },

  // 恢复健康七要素
  {
    id: '42',
    title: '恢复健康的速度，由你自己的七个要素决定',
    content: '恢复健康需要关注气血、循环、毒素、血脂、寒凉、免疫、情绪七个要素。要素改善越多，恢复越快。',
    duration: '10分钟',
    module: '恢复健康七要素',
    season: '第1季',
    courseNumber: 40,
    relatedElements: ['气血', '循环', '毒素', '血脂', '寒凉', '免疫', '情绪'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '43',
    title: '为什么坚持一辈子容易，坚持几个月却很难',
    content: '长期坚持需要建立正确的生活习惯和健康观念。健康调理是长期的过程，不能急于求成。',
    duration: '10分钟',
    module: '恢复健康七要素',
    season: '第1季',
    courseNumber: 41,
    relatedElements: ['情绪', '气血'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },

  // 生活习惯
  {
    id: '44',
    title: '错误的睡眠会让你提前衰老',
    content: '睡眠时间、睡眠质量直接影响健康。熬夜、睡眠不足会加速衰老，导致免疫力下降。',
    duration: '10分钟',
    module: '生活习惯',
    season: '第2季',
    courseNumber: 31,
    relatedElements: ['气血', '免疫', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '45',
    title: '改变坏习惯容易半途而废，是因为误读身体的两个信号',
    content: '身体在改变坏习惯时会有好转反应，很多人误以为是病情加重而放弃。要正确理解身体的信号。',
    duration: '10分钟',
    module: '生活习惯',
    season: '第1季',
    courseNumber: 33,
    relatedElements: ['毒素', '气血'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '46',
    title: '不是疾病年轻化，而是不良生活习惯年轻化',
    content: '疾病年轻化的根本原因是不良生活习惯年轻化。改变生活习惯，才能预防疾病。',
    duration: '10分钟',
    module: '生活习惯',
    season: '第2季',
    courseNumber: 1,
    relatedElements: ['毒素', '气血', '循环', '血脂'],
    relatedDiseases: ['所有慢性病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '47',
    title: '要想活得好，运动不能少',
    content: '运动可以促进气血运行，改善循环，提升免疫力。是健康调理的重要手段。',
    duration: '10分钟',
    module: '生活习惯',
    season: '第3季',
    courseNumber: 2,
    relatedElements: ['气血', '循环', '免疫'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '48',
    title: '对生活习惯的放纵，就是对健康的放弃',
    content: '不良生活习惯会积累毒素、损耗气血、导致疾病。必须严格控制生活习惯。',
    duration: '10分钟',
    module: '生活习惯',
    season: '第3季',
    courseNumber: 4,
    relatedElements: ['毒素', '气血', '循环', '血脂'],
    relatedDiseases: ['所有慢性病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '49',
    title: '坏习惯不改掉，可改换掉',
    content: '不良生活习惯可以用好习惯替代。通过建立新习惯，改掉旧习惯。',
    duration: '10分钟',
    module: '生活习惯',
    season: '第3季',
    courseNumber: 30,
    relatedElements: ['气血', '毒素', '循环'],
    relatedDiseases: ['所有慢性病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '50',
    title: '熬夜是坏习惯之首',
    content: '熬夜会严重损伤气血，导致免疫力下降，循环不畅。是最大的健康杀手。',
    duration: '10分钟',
    module: '生活习惯',
    season: '第3季',
    courseNumber: 43,
    relatedElements: ['气血', '免疫', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },

  // 饮食习惯
  {
    id: '51',
    title: '吃的越好，死的越早',
    content: '过度营养、高热量饮食会导致血脂升高、毒素堆积、气血不足。要均衡饮食。',
    duration: '10分钟',
    module: '饮食习惯',
    season: '第1季',
    courseNumber: 22,
    relatedElements: ['血脂', '毒素', '循环'],
    relatedDiseases: ['高血脂', '心脑血管疾病', '糖尿病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '52',
    title: '身体垃圾越多，越喜欢垃圾食品',
    content: '身体毒素堆积会让人对垃圾食品产生渴望。清理毒素后，饮食会自然改善。',
    duration: '10分钟',
    module: '饮食习惯',
    season: '第1季',
    courseNumber: 44,
    relatedElements: ['毒素', '血脂', '气血'],
    relatedDiseases: ['所有慢性病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '53',
    title: '你误解了营养',
    content: '真正的营养是均衡、天然、适量的饮食。很多人误解了营养，导致营养过剩或不足。',
    duration: '10分钟',
    module: '饮食习惯',
    season: '第3季',
    courseNumber: 12,
    relatedElements: ['气血', '血脂', '毒素'],
    relatedDiseases: ['营养不良', '营养过剩'],
    isHidden: true,
    priority: 4
  },
  {
    id: '54',
    title: '三种剩饭不能吃',
    content: '隔夜绿叶菜、隔夜海鲜、隔夜鸡蛋不能吃，会产生亚硝酸盐等有害物质。',
    duration: '10分钟',
    module: '饮食习惯',
    season: '第2季',
    courseNumber: 23,
    relatedElements: ['毒素', '气血'],
    relatedDiseases: ['食物中毒', '癌症'],
    isHidden: true,
    priority: 3
  },
  {
    id: '55',
    title: '餐桌上的六个常识',
    content: '餐桌上的六个健康常识，包括饮食顺序、食物搭配、饮食时间等。',
    duration: '10分钟',
    module: '饮食习惯',
    season: '第2季',
    courseNumber: 49,
    relatedElements: ['气血', '血脂', '毒素'],
    relatedDiseases: ['所有消化系统疾病'],
    isHidden: true,
    priority: 3
  },
  {
    id: '56',
    title: '别把好吃的当营养',
    content: '好吃的不一定有营养，有营养的不一定好吃。要区分好吃和营养。',
    duration: '10分钟',
    module: '饮食习惯',
    season: '第1季',
    courseNumber: 12,
    relatedElements: ['气血', '血脂', '毒素'],
    relatedDiseases: ['营养不良', '营养过剩'],
    isHidden: true,
    priority: 3
  },

  // 身心灵健康
  {
    id: '57',
    title: '如何快速放下痛苦',
    content: '痛苦源于执念和负面情绪。通过调整心态、释放情绪、培养积极心态，可以快速放下痛苦。',
    duration: '10分钟',
    module: '身心灵健康',
    season: '第2季',
    courseNumber: 26,
    relatedElements: ['情绪', '气血'],
    relatedDiseases: ['心理疾病', '情绪引起的疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '58',
    title: '让身心灵健康，只需要一杆秤',
    content: '用一杆秤来平衡身心健康，包括饮食、运动、睡眠、情绪等方面。',
    duration: '10分钟',
    module: '身心灵健康',
    season: '第2季',
    courseNumber: 22,
    relatedElements: ['情绪', '气血', '循环'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '59',
    title: '幸福也是一种能力，需要训练',
    content: '幸福不是与生俱来的，需要培养和训练。通过建立积极心态、感恩心态，可以提升幸福感。',
    duration: '10分钟',
    module: '身心灵健康',
    season: '第2季',
    courseNumber: 50,
    relatedElements: ['情绪', '气血'],
    relatedDiseases: ['心理疾病', '抑郁症'],
    isHidden: true,
    priority: 3
  },
  {
    id: '60',
    title: '是谁在折磨你，就是自己的性格',
    content: '很多痛苦源于自己的性格。调整性格，可以减少痛苦，改善健康。',
    duration: '10分钟',
    module: '身心灵健康',
    season: '第3季',
    courseNumber: 20,
    relatedElements: ['情绪', '气血'],
    relatedDiseases: ['心理疾病', '情绪引起的疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '61',
    title: '自私是对家人最大的伤害',
    content: '自私会影响家庭关系，导致家庭不和睦。家庭不和睦会影响身心健康。',
    duration: '10分钟',
    module: '身心灵健康',
    season: '第2季',
    courseNumber: 9,
    relatedElements: ['情绪', '气血'],
    relatedDiseases: ['心理疾病', '情绪引起的疾病'],
    isHidden: true,
    priority: 3
  },
  {
    id: '62',
    title: '让心灵健康弥补身体的残缺',
    content: '即使身体有残缺，心灵健康也可以让人生更美好。要培养积极健康的心态。',
    duration: '10分钟',
    module: '身心灵健康',
    season: '第3季',
    courseNumber: 9,
    relatedElements: ['情绪', '气血'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 3
  },
  {
    id: '63',
    title: '亲情可救人，冷漠可杀人',
    content: '家庭的温暖和支持可以给人力量，帮助度过困难。冷漠会让人陷入绝境。',
    duration: '10分钟',
    module: '身心灵健康',
    season: '第3季',
    courseNumber: 23,
    relatedElements: ['情绪', '气血'],
    relatedDiseases: ['心理疾病', '情绪引起的疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '64',
    title: '我们的身体需要一个家，...叫做善良',
    content: '善良是心灵的家，也是身体的保护神。培养善良之心，可以改善身心健康。',
    duration: '10分钟',
    module: '身心灵健康',
    season: '第3季',
    courseNumber: 29,
    relatedElements: ['情绪', '气血'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },

  // 治与调的区别
  {
    id: '65',
    title: '人不是死于疾病，而是死于无知',
    content: '很多疾病是可以预防的，但因为缺乏健康知识，导致悲剧发生。要学习健康知识。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 1,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '66',
    title: '一个害了四代人的矛盾理论，却无人解读',
    content: '错误的健康观念会害了几代人。要树立正确的健康观念，打破错误理论。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 5,
    relatedElements: ['气血', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '67',
    title: '为什么治疗疑难杂症的全是中医',
    content: '中医从整体调理身体，标本兼治。疑难杂症往往是全身性问题，需要整体调理。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 15,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['疑难杂症'],
    isHidden: true,
    priority: 5
  },
  {
    id: '68',
    title: '人民健康，还医于民',
    content: '健康不仅是医生的事，更是每个人的事。要掌握健康知识，管理自己和家人的健康。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 20,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '69',
    title: '如果你重视身体语言，将会有无数次机会救自己',
    content: '身体会通过各种信号告诉我们健康问题。要学会读懂身体的语言，及时发现问题。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 8,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },

  // 中西医的区别
  {
    id: '70',
    title: '如果读懂中西医的区别，小心留下终身遗憾',
    content: '中医和西医的治疗理念不同。中医治本，西医治标。要理解两者的区别，正确选择。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 29,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '71',
    title: '为什么健康离不开中医',
    content: '中医从整体调理身体，标本兼治。健康需要中医的思维和方法。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 30,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '72',
    title: '只图一时之快，都让健康与你无缘',
    content: '西医治标，见效快，但不能治本。中医治本，见效慢，但可以根治。要长远考虑。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 37,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '73',
    title: '解读中西文化的差异，别走入温度的误区',
    content: '中西医理念差异源于文化差异。要理解中医的温度理念，正确调理。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 47,
    relatedElements: ['寒凉', '气血', '循环'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },

  // 体检与自检的区别
  {
    id: '74',
    title: '你读过人体使用说明书吗',
    content: '身体有它自己的使用说明书，就是身体语言和健康知识。要学会使用身体。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 31,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '75',
    title: '你能听懂身体喊救命的语言吗',
    content: '身体会通过症状发出求救信号。要学会读懂这些信号，及时采取措施。',
    duration: '10分钟',
    module: '健康观念',
    season: '第2季',
    courseNumber: 10,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '76',
    title: '自检就是自救',
    content: '自检可以早期发现问题，及时采取措施，避免大病发生。自检是自救的重要手段。',
    duration: '10分钟',
    module: '健康观念',
    season: '第2季',
    courseNumber: 38,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '77',
    title: '六问良性，让你清醒',
    content: '通过六个问题判断肿瘤的良性或恶性。要理性对待体检结果，不要恐慌。',
    duration: '10分钟',
    module: '健康观念',
    season: '第2季',
    courseNumber: 34,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['肿瘤', '癌症'],
    isHidden: true,
    priority: 4
  },
  {
    id: '78',
    title: '指标正常，不等于健康',
    content: '体检指标正常不一定代表健康。很多疾病在早期指标正常，但身体已经有问题。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 6,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },

  // 健康观念
  {
    id: '79',
    title: '我帮你算算你的健康值多少钱',
    content: '健康是最大的财富。计算健康的价值，让人重视健康。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 51,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '80',
    title: '亚健康是个筐，找不到病因往里装',
    content: '亚健康不是原因，而是结果。要找到亚健康的真正原因，才能解决。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 45,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['亚健康'],
    isHidden: true,
    priority: 4
  },
  {
    id: '81',
    title: '把好健康一道关，观念能救一代人',
    content: '正确的健康观念可以救人。要树立正确的健康观念，影响身边的人。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 19,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 5
  },
  {
    id: '82',
    title: '身体与信用卡一样，一旦透支就叫过劳死',
    content: '身体的健康像信用卡一样，可以透支，但透支多了就会出问题。要避免过度透支。',
    duration: '10分钟',
    module: '健康观念',
    season: '第2季',
    courseNumber: 17,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['过劳死', '慢性疲劳'],
    isHidden: true,
    priority: 4
  },
  {
    id: '83',
    title: '决定健康的三个要素',
    content: '决定健康的三个要素是饮食、运动、心态。要平衡好这三个要素。',
    duration: '10分钟',
    module: '健康观念',
    season: '第2季',
    courseNumber: 28,
    relatedElements: ['气血', '循环', '毒素', '情绪'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '84',
    title: '健康观念拯救家族',
    content: '一个家族的健康观念会影响家族成员的健康。正确的健康观念可以拯救整个家族。',
    duration: '10分钟',
    module: '健康观念',
    season: '第2季',
    courseNumber: 9,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '85',
    title: '一场病，救了全家人的命',
    content: '疾病可以让人觉醒，重视健康。一场病可能救了全家人的命。',
    duration: '10分钟',
    module: '健康观念',
    season: '第2季',
    courseNumber: 11,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },

  // 心脑血管疾病
  {
    id: '86',
    title: '一个成语拯救2.5亿个家庭',
    content: '通过"治标治本"这个成语，理解心脑血管疾病的预防和调理。',
    duration: '10分钟',
    module: '心脑血管疾病',
    season: '第1季',
    courseNumber: 6,
    relatedElements: ['循环', '气血', '血脂', '寒凉'],
    relatedDiseases: ['高血压', '心脏病', '中风'],
    isHidden: true,
    priority: 5
  },
  {
    id: '87',
    title: '如何让你家人远离心脑血管疾病',
    content: '通过调理气血、循环、血脂、寒凉等要素，预防和改善心脑血管疾病。',
    duration: '10分钟',
    module: '心脑血管疾病',
    season: '第1季',
    courseNumber: 7,
    relatedElements: ['循环', '气血', '血脂', '寒凉'],
    relatedDiseases: ['高血压', '心脏病', '中风'],
    isHidden: true,
    priority: 5
  },
  {
    id: '88',
    title: '如何让家人远离心脑血管疾病',
    content: '心脑血管疾病可以通过调理预防和改善。要从根本上解决问题。',
    duration: '10分钟',
    module: '心脑血管疾病',
    season: '第1季',
    courseNumber: 8,
    relatedElements: ['循环', '气血', '血脂', '寒凉'],
    relatedDiseases: ['高血压', '心脏病', '中风'],
    isHidden: true,
    priority: 5
  },

  // 糖尿病
  {
    id: '89',
    title: '解读糖尿病的七个误区，你有可能救人一命',
    content: '很多人对糖尿病有误解，导致病情恶化。要正确理解糖尿病，避免误区。',
    duration: '10分钟',
    module: '糖尿病',
    season: '第1季',
    courseNumber: 52,
    relatedElements: ['气血', '血脂', '循环', '毒素'],
    relatedDiseases: ['糖尿病', '高血糖'],
    isHidden: true,
    priority: 5
  },
  {
    id: '90',
    title: '不是疾病年轻化了，而是坏习惯年轻化了',
    content: '糖尿病等疾病年轻化的原因是不良生活习惯年轻化。要改变生活习惯。',
    duration: '10分钟',
    module: '糖尿病',
    season: '第2季',
    courseNumber: 1,
    relatedElements: ['血脂', '气血', '毒素', '循环'],
    relatedDiseases: ['糖尿病', '高血糖'],
    isHidden: true,
    priority: 5
  },

  // 其他疾病
  {
    id: '91',
    title: '让每个家庭都有一个懂健康的孩子',
    content: '培养孩子的健康意识，让孩子了解健康知识，可以预防很多疾病。',
    duration: '10分钟',
    module: '健康观念',
    season: '第4季',
    courseNumber: 2,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['儿童疾病'],
    isHidden: true,
    priority: 4
  },
  {
    id: '92',
    title: '比流感更可怕的误区',
    content: '对流感有很多误区，导致处理不当。要正确认识流感，避免误区。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 24,
    relatedElements: ['免疫', '气血', '毒素'],
    relatedDiseases: ['感冒', '流感'],
    isHidden: true,
    priority: 4
  },
  {
    id: '93',
    title: '方向转换，奇迹出现',
    content: '改变调理方向，从治标转向治本，奇迹就会出现。',
    duration: '10分钟',
    module: '健康观念',
    season: '第1季',
    courseNumber: 35,
    relatedElements: ['气血', '循环', '毒素'],
    relatedDiseases: ['所有疾病'],
    isHidden: true,
    priority: 4
  },
];

// 疾病相关的症状映射
export const DISEASE_SYMPTOM_MAP: Record<string, number[]> = {
  '高血压': [72, 48, 49, 55, 75],
  '心脏病': [48, 49, 50, 55, 75],
  '中风': [48, 49, 75],
  '糖尿病': [73, 74, 68, 69, 70, 91],
  '高血脂': [71, 68, 69, 70],
  '痛风': [68, 69, 70],
  '肾病': [64, 65, 66, 67, 68, 69, 70],
  '肝胆疾病': [68, 69, 70, 86, 87, 88, 89],
  '过敏': [94, 31, 32, 33, 36, 37],
  '静脉曲张': [59, 55, 57],
  '红斑狼疮': [92, 94],
  '湿疹': [93],
  '低血压': [75, 55],
  '胃病': [86, 87, 88, 89, 90],
  '胆结石': [68, 69, 70, 86, 87, 88, 89],
  '肺漏': [36, 37, 38, 39, 40],
  '月子病': [76, 77, 78, 79, 80, 81, 82, 83, 84],
  '早产': [76, 77, 78, 79, 80, 81, 82, 83, 84],
  '气血不足': [1, 2, 3, 4, 5, 8, 10, 14, 15, 48, 49, 55, 58, 85],
  '循环不畅': [48, 49, 55, 57, 59, 60, 61, 62, 63, 75],
  '毒素堆积': [68, 69, 70, 91, 92, 93, 95, 96, 97],
  '寒凉体质': [4, 10, 11, 34, 55, 74, 75, 92, 93],
  '免疫力低下': [34, 92, 94, 98],
  '情绪问题': [85, 5, 10, 15],
  '血脂高': [71, 68, 69, 70, 91],
};
